### ISSUE TITLE
Impossible to us items in bags

### ISSUE THREAD

**Issue by Darkhibaris** [BloodDragon2580/QuestTrackerMover#1]
Hi,
I get the following error message when I right click on an item in my bags. So I can't use the items.
![quest_error](https://user-images.githubusercontent.com/118050158/202772579-248a20d0-7b42-468b-8e45-51ec5778a530.jpg)

--------------
3x [ADDON_ACTION_FORBIDDEN] L'AddOn 'QuestTrackerMover' a tenté d'appeler la fonction protégée 'UNKNOWN()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1409: in function <Interface/FrameXML/ContainerFrame.lua:1318>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1461: in function <Interface/FrameXML/ContainerFrame.lua:1448>

**Comment by BloodDragon2580** [comment]
This is not due to the QuestTrackerMover but to Blizzard. Blizzard still has a lot of problems at the moment. But I can only recommend that you temporarily deactivate the addon because you can now move the quest tracker at retail without an addon.

**Comment by Darkhibaris** [comment]
Okay. Thank you for your help :)
